Added Command (Completed the TODO)
KableKo/silent-type pull request #1
Opened 2020-11-14 21:38 UTC by c0dine

Added a command that allows you to toggle `--on` and `--off` using `.silent-type`
It works right away too! I will be willing to make this into settings but you can already turn commands off and on using powercords `Plugins > Silent Type > Toggle`

2020-11-14 22:34 UTC, kablekompany reviewed
I believe for this method you'll need to pull in component settings as a constant and let it set the switch (which you're doing already, but it's not actually referencing or injecting a settings conf
`powercord.api.settings.registerSettings` maybe? 
unsure but i can't get it to toggle. Turns off and stays off (showing typing notifs)

2020-11-15 03:41 UTC, kablekompany requested changes
I think since you check on in configurations for true, that is our stationary setter. And true is on false is off. I've noted the recommendation. Let me know if you agree.

2020-11-15 03:41 UTC, kablekompany commented on index.js
> +            this.settings.set('on')
`this.settings.set(false)`

For feasibility sake I'd like to change I/O to a Boolean. Easier to manipulate if a settings panel is added later too

2020-11-15 03:41 UTC, kablekompany commented on index.js
> +            this.settings.set('on')
`this.settings.set(true)`

see next line comment re: boolean indication I/O

2020-11-15 03:41 UTC, kablekompany commented on index.js
> +                const on = this.settings.get('on')
```suggestion
                const on = this.settings.get()
```

2020-11-16 03:30 UTC, c0dine commented
```javascript
this.settings.set()
```
This is an api thing used with multiple settings. I could reassign it but it has no actual effect to the actual performance.

2020-11-16 06:37 UTC, kablekompany commented
Sweet. I'll test and merge if all works out. Will be at injected client in a few hours.

2020-11-16 22:43 UTC, kablekompany commented
LGTM 
tested and works 
Thanks for the contribution

2020-11-16 22:43 UTC, merged

2020-11-16 23:02 UTC, c0dine commented
/shrug No problem